### ISSUE TITLE
Ability to ignore root key

### ISSUE THREAD

**Issue by infertux** [acatton/yamlkeysdiff#2]
Feature request :smile: 

``` bash
% grep '' en.yml fr.yml 
en.yml:en:
en.yml:  current_locale: English
en.yml:  hi: Hi
fr.yml:fr:
fr.yml:  current_locale: Français
fr.yml:  hi: Salut

% ./dist/build/yamlkeysdiff/yamlkeysdiff en.yml fr.yml
> en:current_locale
> en:hi
< fr:current_locale
< fr:hi
```

It'd be great to be able to ignore the root key (`en`/`fr` in this example) with something like that:

```
% ./dist/build/yamlkeysdiff/yamlkeysdiff --ignore-root-key en.yml fr.yml
# exit 0
```

**Comment by acatton** [comment]
What about having a special syntax to specify the root of what you want to compare? Like `file.yml#key:subkey:subsubkey`

You would run something like this:

``` sh
yamlkeysdiff "en.yml#en" "fr.yml#fr"
```

I'm just suggesting, not saying this is the right approach ;) .

**Comment by infertux** [comment]
It feels YAGNI to me, ignoring the root key is already a bit of a weird feature, but knock yourself out :)

**Comment by acatton** [comment]
I'm working on it then ;) .

**Comment by acatton** [comment]
@infertux `yamlkeysdiff "en.yml#en" "fr.yml#fr"` should work.

**Comment by infertux** [comment]
@acatton Hooray! Thanks heaps, I shaved like 60 seconds off my CI script with https://github.com/buckybox/webstore/commit/96e24c2bafffa08c9f4a760e2eadf0302bd09b77 :smile:. However, it still feels a bit dirty checking in binaries into the repo. Any chance to publish it on http://hackage.haskell.org/ sometime so I could use `cabal install`?

**Comment by acatton** [comment]
@infertux you also deleted code. That's what is important :) .

**Comment by infertux** [comment]
@acatton I _love_ deleting code! Less code means less bugs :)
